---
# tasks file for roles/cluster

# Join the rest

- name: "DEBUG | Join to master {{ kubernetes_version }}"
  debug:
    msg: kubeadm join {{ lb_address }}:{{ lb_port }} --token 69ed18.ccfss6dkqpuhqsu9 --discovery-token-ca-cert-hash sha256:{{ hostvars['master1']['token_sha256']['stdout'] }} --control-plane --certificate-key {{ certificate_key }}
  become_user: root
  tags:
    - cluster
    - joining

- name: "INIT | Join to master {{ kubernetes_version }}"
  shell: kubeadm join {{ lb_address }}:{{ lb_port }} --token 69ed18.ccfss6dkqpuhqsu9 --discovery-token-ca-cert-hash sha256:{{ hostvars['master1']['token_sha256']['stdout'] }} --control-plane --certificate-key {{ certificate_key }}
  become_user: root
  tags:
    - cluster
    - joining

- name: "INIT | Create Kubernetes config directory"
  file:
    path: /home/{{ ansible_ssh_user }}/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755
  become_user: root
  tags:
    - cluster
    - joining

- name: "INIT | Copy admin.conf to config directory"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_ssh_user }}/.kube/config
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
    remote_src: yes
    backup: yes
  become_user: root
  tags:
    - cluster
    - joining
