# https://medium.com/@kosta709/kubernetes-by-kubeadm-config-yamls-94e2ee11244
# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1
# https://kubernetes-io-vnext-staging.netlify.com/docs/setup/production-environment/tools/kubeadm/high-availability/
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: "{{ token }}"
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
certificateKey: "{{ certificate_key }}"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: kubernetes
certificatesDir: /etc/kubernetes/pki
kubernetesVersion: "{{ kubernetes_version }}"
controlPlaneEndpoint: "{{ lb_address }}:{{ lb_port }}"
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServer:
  certSANs:
  - '*.k8s.cluster.com'
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 8m0s
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
