version: '3'

services:
  dnscore:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: dnscore:latest
    ports:
    - "53:53/udp"
    command: -conf /root/Corefile
    volumes:
    - ./data:/root
