---
# tasks file for roles/cluster

# reference: git clone https://github.com/rak8s/rak8s.git
# reference: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

- name: "INFO | host {{ ansible_ssh_host }}"
  debug:
    msg: |
       System: {{ ansible_system }}
       OS Family: {{ linux_architecture }}
       Distribution: {{ ansible_distribution }}
       Release: {{ ansible_distribution_release }}
       Architecture: {{ ansible_architecture }}
       IPV4: {{ ansible_default_ipv4.address }}
  tags:
    - cluster

- name: "PREPARE | Install openssl and ca package on debian systems"
  apt:
    name: [ ca-certificates, openssl ]
    state: present
    update_cache: yes
    force_apt_get: yes
  become_user: root
  tags:
    - cluster

- name: "PREPARE | Disable Swap"
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  ignore_errors: True
  become_user: root
  tags:
    - cluster

- name: "RESET | Reset Kubernetes Master"
  shell: kubeadm reset -f
  register: kubeadm_reset
  become_user: root
  tags:
    - cluster

- name: "PREPARE | Deploy Docker daemon.json."
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  become_user: root
  tags:
    - cluster

- name: "PREPARE | Ensure docker deamon is restarted"
  service:
    name: docker
    state: restarted
  become_user: root
  tags:
    - cluster
