---
# tasks file for roles/cluster

# reference: git clone https://github.com/rak8s/rak8s.git

- name: "INFO | host {{ ansible_ssh_host }}"
  debug:
    msg: |
       System: {{ ansible_system }}
       OS Family: {{ linux_architecture }}
       Distribution: {{ ansible_distribution }}
       Release: {{ ansible_distribution_release }}
       Architecture: {{ ansible_architecture }}
       IPV4: {{ ansible_default_ipv4.address }}

- name: "RESET | Reset Kubernetes Master"
  shell: kubeadm reset -f
  register: kubeadm_reset
  become_user: root

- name: "INIT | Initialize Master {{ kubernetes_version }}"
  shell: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --token={{ token }} --kubernetes-version={{ kubernetes_version }} --pod-network-cidr={{ podnet }}
  register: kubeadm_init
  when: kubeadm_reset is succeeded
  become_user: root

- name: "INIT | Create Kubernetes config directory"
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755
  become_user: root

- name: "INIT | Copy admin.conf to config directory"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    backup: yes
  when: kubeadm_init
  become_user: root 

- name: "INIT | Create Kubernetes config directory"
  file:
    path: /home/{{ ansible_ssh_user }}/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755
  become_user: root

- name: "INIT | Copy admin.conf to config directory"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_ssh_user }}/.kube/config
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
    remote_src: yes
    backup: yes
  when: kubeadm_init
  become_user: root 

- name: "DEBUG | Joining cluster"
  debug:
    msg: kubeadm join --ignore-preflight-errors=all --token {{ token }} {{ groups['k8smaster'][0] }}.k8s.cluster.com:6443 --discovery-token-unsafe-skip-ca-verification

- name: "INIT | Join Kubernetes Cluster"
  shell: kubeadm join --ignore-preflight-errors=all --token {{ token }} {{ groups['k8smaster'][0] }}.k8s.cluster.com:6443 --discovery-token-unsafe-skip-ca-verification
  when: kubeadm_reset is succeeded
  register: kubeadm_join
  become_user: root

- name: "INIT | Install Flannel (Networking)"
  shell: "curl -sSL https://rawgit.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml | kubectl create -f -"
  args:
    warn: false

- name: "INIT | Poke kubelet"
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke
  become_user: root
