---
# tasks file for roles/cluster

# reference: git clone https://github.com/rak8s/rak8s.git

- name: "INFO | host {{ ansible_ssh_host }}"
  debug:
    msg: |
       System: {{ ansible_system }}
       OS Family: {{ linux_architecture }}
       Distribution: {{ ansible_distribution }}
       Release: {{ ansible_distribution_release }}
       Architecture: {{ ansible_architecture }}
       IPV4: {{ ansible_default_ipv4.address }}
  tags:
    - cluster

- name: "Install ca package on debian systems"
  apt:
    name: ca-certificates
    state: present
    update_cache: yes
  become_user: root
  tags:
    - cluster

- name: "RESET | Reset Kubernetes Master"
  shell: kubeadm reset -f
  register: kubeadm_reset
  become_user: root
  tags:
    - cluster

- name: Deploy Docker daemon.json.
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  become_user: root
  tags:
    - cluster

- name: Ensure docker deamon is restarted
  service:
    name: docker
    state: restarted
  become_user: root
  tags:
    - cluster

- name: "DEBUG | Initialize cluster"
  debug:
    msg: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --apiserver-cert-extra-sans *.k8s.cluster.com --token={{ token }} --kubernetes-version={{ kubernetes_version }} --pod-network-cidr={{ podnet }} --upload-certs
  tags:
    - cluster

- name: "INIT | Initialize Master {{ kubernetes_version }}"
  shell: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --apiserver-cert-extra-sans *.k8s.cluster.com --token={{ token }} --kubernetes-version={{ kubernetes_version }} --pod-network-cidr={{ podnet }} --upload-certs
  register: kubeadm_init
  when: kubeadm_reset is succeeded
  become_user: root
  tags:
    - cluster

- name: copy certificate authority to trusted ca path of the os
  copy:
    src: '{{ item }}'
    dest: '/usr/local/share/ca-certificates'
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - /etc/kubernetes/pki/ca.crt
  notify:
    - update trusted ca debian

- name: "INIT | Create Kubernetes config directory"
  file:
    path: /home/{{ ansible_ssh_user }}/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755
  become_user: root
  tags:
    - cluster

- name: "INIT | Copy admin.conf to config directory"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_ssh_user }}/.kube/config
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
    remote_src: yes
    backup: yes
  when: kubeadm_init
  become_user: root
  tags:
    - cluster 

- name: "DEBUG | Joining cluster"
  debug:
    msg: kubeadm join --ignore-preflight-errors=all --token {{ token }} --discovery-token-ca-cert-hash {{ token_sha256 }} master1.k8s.cluster.com:6443
  tags:
    - worker

- name: "INIT | Join Kubernetes Cluster"
  shell: kubeadm join --ignore-preflight-errors=all --token {{ token }} --discovery-token-ca-cert-hash {{ token_sha256 }} master1.k8s.cluster.com:6443
  when: kubeadm_reset is succeeded
  register: kubeadm_join
  become_user: root
  tags:
    - worker

- name: "INIT | Remove flannel link"
  shell: "ip link delete flannel.1"
  become_user: root
  tags:
    - cluster

- name: "INIT | Install Flannel (Networking)"
  shell: "curl -sSL https://rawgit.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml | kubectl create -f -"
  args:
    warn: false
  tags:
    - cluster

- name: "INIT | Poke kubelet"
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke
  become_user: root
  tags:
    - cluster

