---
# tasks file for roles/cluster

- name: "INFO | host {{ ansible_ssh_host }}"
  debug:
    msg: |
       System: {{ ansible_system }}
       OS Family: {{ linux_architecture }}
       Distribution: {{ ansible_distribution }}
       Release: {{ ansible_distribution_release }}
       Architecture: {{ ansible_architecture }}
       IPV4: {{ ansible_default_ipv4.address }}
  tags:
    - cluster

- name: "FINALIZING | Poke kubelet"
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  become_user: root
  tags:
    - cluster

- name: "FINALIZING | Remove No schedule taints"
  shell: "kubectl taint nodes {{ inventory_hostname }} node-role.kubernetes.io/master:NoSchedule-"
  tags:
    - cluster
