apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: jenkins
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jenkins
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      containers:
      - image: kodbasen/jenkins-arm:2.7.1
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
          name: web
        - containerPort: 50000
          protocol: TCP
          name: slaves
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkinshome
      volumes:
      - name: jenkinshome
        persistentVolumeClaim:
          claimName: jenkins
